"""
aiXapply data generation pipeline.

Stage: prediction-based filtering.
Purpose: remove samples that fail across multiple inference providers.
Inputs: result_dict.json and per-language passed parquet datasets.
Outputs: per-language filtered parquet datasets.
"""

import os
import json
import argparse
import pandas as pd

from pathlib import Path
from collections import Counter
from datasets import Dataset


def parse_args():
    parser = argparse.ArgumentParser(
        description="Remove incorrect samples based on evaluation results"
    )
    parser.add_argument(
        "--result-file",
        default="dataset/synthetic_data/predictions_result/result_dict.json",
        help="Result file generated by extract_jsonl_data.py"
    )
    parser.add_argument(
        "--data-dir",
        default="dataset/synthetic_data/judge_processed",
        help="Original dataset directory (contains *_passed.parquet files)"
    )
    parser.add_argument(
        "--output-dir",
        default="dataset/synthetic_data/filtered",
        help="Output directory (contains dataset after removing incorrect samples)"
    )
    parser.add_argument(
        "--method",
        default="pygments",
        choices=["ast", "pygments"],
        help="Evaluation method (corresponds to key in result_dict.json)"
    )
    parser.add_argument(
        "--languages",
        nargs="*",
        default=None,
        help="Specify language list to process, default processes all languages"
    )
    parser.add_argument(
        "--min-error-count",
        type=int,
        default=5,
        help="Minimum error count threshold. Samples with at least this many failures will be removed (default: 5)"
    )
    parser.add_argument(
        "--dynamic-threshold",
        action="store_true",
        help="Enable dynamic threshold selection based on the observed error-count distribution"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only show operations to be performed, do not actually write to files"
    )
    parser.add_argument(
        "--merge-output",
        action="store_true",
        help="Merge all language data into a single file"
    )
    parser.add_argument(
        "--merge-filename",
        default="all_languages_filtered.parquet",
        help="Name of merged file"
    )
    parser.add_argument(
        "--show-error-details",
        dest="show_error_details",
        action="store_true",
        default=True,
        help="Show detailed sample indices for each error count"
    )
    parser.add_argument(
        "--no-show-error-details",
        dest="show_error_details",
        action="store_false",
        help="Hide detailed sample indices for each error count"
    )
    parser.add_argument(
        "--max-samples-display",
        type=int,
        default=50,
        help="Maximum number of samples to display for each error count (default is 50, set to 0 to display all)"
    )
    return parser.parse_args()


def select_dynamic_threshold(count_distribution: Counter, min_error_count: int, model_count: int) -> int:
    """
    Select an error-count threshold from the observed distribution.

    The default min_error_count is 5, so the initial comparison remains compatible with
    the previous 4-vs-5 behavior. If the lower count bucket is larger than the next
    bucket, the threshold moves up and continues checking higher failure counts.
    """
    if model_count <= 0:
        return min_error_count

    max_times = max(count_distribution.keys(), default=0)
    if max_times <= 0:
        return min_error_count

    threshold = max(1, min(min_error_count - 1, max_times))

    while threshold < max_times:
        current_count = count_distribution.get(threshold, 0)
        next_count = count_distribution.get(threshold + 1, 0)

        if current_count > next_count:
            threshold += 1
        else:
            break

    return min(threshold, model_count)


def load_result_dict(result_file: str) -> dict:
    """Load evaluation result file"""
    if not os.path.exists(result_file):
        raise FileNotFoundError(f"Result file not found: {result_file}")
    
    with open(result_file, 'r', encoding='utf-8') as f:
        return json.load(f)


def extract_errors_by_language(result_dict: dict, method: str, min_error_count: int = 1, dynamic_threshold: bool = False) -> dict:
    """
    Extract error index list for each language from result dictionary, supporting filtering by error count threshold.
    
    Args:
        result_dict: Complete result dictionary
        method: Evaluation method (ast or pygments)
        min_error_count: Minimum error count threshold, only samples that fail more than this value will be removed
        dynamic_threshold: Whether to enable dynamic threshold selection. If True, then the threshold is selected dynamically
                           based on the observed error-count distribution.
    Returns:
        Dictionary of {language: {"errors_list": error index list, "model_count": model count, "error_counts": Counter object, "threshold": actual used threshold}}
    """
    if method not in result_dict:
        raise KeyError(f"Method '{method}' not found in result file, available methods: {list(result_dict.keys())}")
    
    method_results = result_dict[method]
    
    # First step: collect all model error lists by language
    all_errors_by_lang = {}  # {language: [list of all error indices (including duplicates)]}
    model_count_by_lang = {}  # {language: model count}
    
    for file_key, data in method_results.items():
        lang = data.get("language")
        errors_list = data.get("errors_list", [])
        
        if lang:
            if lang not in all_errors_by_lang:
                all_errors_by_lang[lang] = []
                model_count_by_lang[lang] = 0
            all_errors_by_lang[lang].extend(errors_list)
            model_count_by_lang[lang] += 1
    
    # Second step: count error count for each index and filter by threshold
    errors_by_lang = {}
    
    for lang, all_errors in all_errors_by_lang.items():
        error_counter = Counter(all_errors)
        model_count = model_count_by_lang[lang]
        
        # Dynamic threshold selection
        if dynamic_threshold:
            count_distribution = Counter(error_counter.values())
            actual_threshold = select_dynamic_threshold(count_distribution, min_error_count, model_count)
        else:
            actual_threshold = min_error_count
        
        # Filter by threshold: only keep indices with error count >= actual_threshold
        filtered_errors = [idx for idx, count in error_counter.items() if count >= actual_threshold]
        
        errors_by_lang[lang] = {
            "errors_list": sorted(filtered_errors),
            "model_count": model_count,
            "error_counts": error_counter,  # Keep complete count information for display
            "threshold": actual_threshold  # Record actual used threshold
        }
    
    return errors_by_lang


def print_error_details_by_count(error_counts: Counter, model_count: int, max_display: int = 50):
    """
    Print detailed sample indices by error count.
    
    Args:
        error_counts: Counter object, {index: error count}
        model_count: Total model count
        max_display: Maximum number of samples to display for each error count, 0 means display all
    """
    # Group by error count
    errors_by_count = {}  # {error count: [index list]}
    for idx, count in error_counts.items():
        if count not in errors_by_count:
            errors_by_count[count] = []
        errors_by_count[count].append(idx)
    
    # Print by error count from high to low
    for count in sorted(errors_by_count.keys(), reverse=True):
        indices = sorted(errors_by_count[count])
        total = len(indices)
        
        # Calculate error rate (percentage of this count over total model count)
        error_rate = count / model_count * 100 if model_count > 0 else 0
        
        print(f"    Failed {count} time(s) ({error_rate:.1f}%): {total} sample(s)")
        
        if count < 4:
            continue
        # Display sample indices
        if max_display == 0 or total <= max_display:
            # Display all
            print(f"      Indices: {indices}")
        else:
            # Display partial
            display_indices = indices[:max_display]
            print(f"      Indices (first {max_display}): {display_indices}")
            print(f"      ... {total - max_display} more not shown")


def filter_dataset(data_path: Path, errors_list: list) -> tuple:
    """
    Remove incorrect samples from dataset.
    
    Args:
        data_path: Dataset file path
        errors_list: List of indices to remove
    
    Returns:
        (Filtered Dataset, original count, removed count)
    """
    # Use pandas to load parquet file
    df = pd.read_parquet(data_path)
    original_count = len(df)
    
    if not errors_list:
        # No error samples, return original data
        return Dataset.from_pandas(df), original_count, 0
    
    # Ensure indices are within valid range
    valid_errors = [idx for idx in errors_list if 0 <= idx < original_count]
    
    if len(valid_errors) != len(errors_list):
        invalid = set(errors_list) - set(valid_errors)
        print(f"  Ignore indices out of range: {invalid}")
    
    # Create list of indices to keep
    keep_indices = [i for i in range(original_count) if i not in set(valid_errors)]
    
    # Filter data
    filtered_df = df.iloc[keep_indices].reset_index(drop=True)
    filtered_dataset = Dataset.from_pandas(filtered_df)
    
    return filtered_dataset, original_count, len(valid_errors)


def resolve_data_path(data_dir: str, lang: str) -> Path:
    """Resolve the dataset file produced by judge_processor.py."""
    return Path(data_dir) / f"{lang}_passed.parquet"


def main():
    args = parse_args()
    
    # Load result file
    print(f"Loading result file: {args.result_file}")
    result_dict = load_result_dict(args.result_file)
    
    # Extract error index list for each language (with error count statistics)
    errors_by_lang = extract_errors_by_language(result_dict, args.method, args.min_error_count, args.dynamic_threshold)
    
    print(f"\nEvaluation method: {args.method}")
    print(f"Data directory: {args.data_dir}")
    print(f"Output directory: {args.output_dir}")
    if args.dynamic_threshold:
        print(f"Dynamic threshold selection: enabled (based on observed error-count distribution)")
    else:
        print(f"Minimum error count threshold: {args.min_error_count}")
    print(f"\nFound {len(errors_by_lang)} language evaluation results: {errors_by_lang}")
    for lang, data in sorted(errors_by_lang.items()):
        errors = data["errors_list"]
        model_count = data["model_count"]
        error_counts = data["error_counts"]
        actual_threshold = data["threshold"]
        
        # Count distribution of each error count
        count_distribution = Counter(error_counts.values())
        dist_str = ", ".join([f"{c} times:{n} samples" for c, n in sorted(count_distribution.items())])
        
        print(f"- {lang}: {model_count} models, {len(error_counts)} different error indices")
        print(f"  Error count distribution: {dist_str}")
        if args.dynamic_threshold:
            print(f"  Dynamic threshold selection: threshold={actual_threshold}")
        print(f"  Error samples with threshold (>={actual_threshold}): {len(errors)} samples")
        if errors and len(errors) <= 20:
            print(f"  Error indices: {errors}")
        
        # Print detailed error count distribution
        if args.show_error_details:
            print(f"  === Detailed error distribution ===")
            print_error_details_by_count(error_counts, model_count, args.max_samples_display)
    
    # If language list is specified, only process specified languages
    if args.languages:
        errors_by_lang = {k: v for k, v in errors_by_lang.items() if k in args.languages}
        print(f"\nProcessed {len(errors_by_lang)} languages after filtering: {list(errors_by_lang.keys())}")
    elif "languages" in errors_by_lang:
        errors_by_lang.pop("languages")
        print(
            "\n Skipped [languages] by default to avoid filtering the merged dataset "
            "together with per-language datasets. Use --languages all_languages to process it explicitly."
        )
    
    # Create output directory
    output_dir = Path(args.output_dir)
    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)
    
    # Process each language
    print("\n" + "=" * 80)
    print("Start processing dataset")
    print("=" * 80)
    
    all_filtered_data = []  # For merging output
    stats = []
    
    for lang, lang_data in sorted(errors_by_lang.items()):
        errors_list = lang_data["errors_list"]
        model_count = lang_data["model_count"]
        actual_threshold = lang_data["threshold"]
        
        data_path = resolve_data_path(args.data_dir, lang)
        
        if not data_path.exists():
            print(f"\n[{lang}] Data file not found: {data_path}")
            continue
        
        print(f"\nProcessing [{lang}]...")
        print(f"  Data file: {data_path}")
        print(f"  Model count: {model_count}")
        print(f"  Error threshold: >={actual_threshold} times")
        print(f"  Indices to remove: {len(errors_list)}")
        
        try:
            filtered_dataset, original_count, removed_count = filter_dataset(data_path, errors_list)
            final_count = len(filtered_dataset)
            
            print(f"  Original samples: {original_count}")
            print(f"  Removed samples: {removed_count}")
            print(f"  Remaining samples: {final_count}")
            
            stats.append({
                "language": lang,
                "original": original_count,
                "removed": removed_count,
                "final": final_count,
                "model_count": model_count,
                "min_error_count": args.min_error_count
            })
            
            if not args.dry_run:
                output_path = output_dir / f"{lang}_filtered.parquet"
                # Convert to pandas DataFrame and save
                filtered_dataset.to_parquet(str(output_path))
                print(f" Saved: {output_path}")
                
                if args.merge_output:
                    # Add language identifier column
                    df = filtered_dataset.to_pandas()
                    df['language'] = lang
                    all_filtered_data.append(df)
            else:
                print(f" [DRY-RUN] Will save to: {output_dir / f'{lang}_filtered.parquet'}")
                
        except Exception as e:
            print(f" Processing failed: {e}")
            continue
    
    # Merge output
    if args.merge_output and all_filtered_data and not args.dry_run:
        print(f"\nMerging all language data...")
        merged_df = pd.concat(all_filtered_data, ignore_index=True)
        merged_path = output_dir / args.merge_filename
        merged_df.to_parquet(str(merged_path))
        print(f" Saved merged file: {merged_path} ({len(merged_df)} records)")
    
    # Print summary of statistics
    print("\n" + "=" * 100)
    threshold_label = "dynamic" if args.dynamic_threshold else str(args.min_error_count)
    print(f"Processing summary: error threshold >={threshold_label} times")
    print("=" * 100)
    print(f"{'Language':<15} {'Model count':<8} {'Original':<10} {'Removed':<10} {'Remaining':<10} {'Retention rate':<10}")
    print("-" * 70)
    
    total_original = 0
    total_removed = 0
    total_final = 0
    
    for s in stats:
        retention_rate = s['final'] / s['original'] * 100 if s['original'] > 0 else 0
        print(f"{s['language']:<15} {s['model_count']:<8} {s['original']:<10} {s['removed']:<10} {s['final']:<10} {retention_rate:.1f}%")
        total_original += s['original']
        total_removed += s['removed']
        total_final += s['final']
    
    print("-" * 70)
    total_retention = total_final / total_original * 100 if total_original > 0 else 0
    print(f"{'Total':<15} {'-':<8} {total_original:<10} {total_removed:<10} {total_final:<10} {total_retention:.1f}%")
    print("=" * 100)
    
    # Save statistics information
    if not args.dry_run:
        stats_path = output_dir / "filter_stats.json"
        with open(stats_path, 'w', encoding='utf-8') as f:
            json.dump({
                "method": args.method,
                "min_error_count": args.min_error_count,
                "source_result_file": args.result_file,
                "source_data_dir": args.data_dir,
                "languages": stats,
                "total": {
                    "original": total_original,
                    "removed": total_removed,
                    "final": total_final,
                    "retention_rate": total_retention
                }
            }, f, indent=2, ensure_ascii=False)
        print(f"\nStatistics information saved: {stats_path}")
    
    print("\nProcessing completed!")


if __name__ == "__main__":
    main()
